services:
  - type: web
    name: nourishlab
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn nourishlab.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: NODE_VERSION
        value: 22.22.0
